### ISSUE TITLE
Flask NullPointerException

### ISSUE THREAD

**Issue by Shymune** [RacerDelux/MagicalPotionsAndBrews#3] opened 2016-07-12 04:18 UTC
java.lang.NullPointerException: Unexpected error at: com.squaresuits.magicalpotionsandbrews.items.ItemPotionFlask.func_77661_b(ItemPotionFlask.java:264)

While hovering over the flask and holding shift.

java.lang.ArrayIndexOutOfBoundsException: 2
at com.squaresuits.magicalpotionsandbrews.registry.FlaskRecipe.getNameOfItem(FlaskRecipe.java:87)

Occurred while I was looking at a recipe in JEI.

**Comment by RacerDelux** [comment] 2016-07-12 04:37
Please supply full crash log

**Comment by Shymune** [comment] 2016-07-12 04:40
NullPointerException: http://hastebin.com/fehefivoge.coffee
ArrayIndexOutOfBoundsException: http://hastebin.com/qonetemufo.vhdl

**Comment by RacerDelux** [comment] 2016-07-12 04:40
Odd. I am unable to reproduce the error on my dev side. Will continue looking into this.

**Comment by RacerDelux** [comment] 2017-11-29 15:59
This is a pretty old bug. It should be fixed by now and I am closing this. If you ever come across it again, feel free to reopen.

**Closed as completed by RacerDelux** 2017-11-29 15:59 UTC
Labels: bug, CNR
